### ISSUE TITLE
q re:git semver matching

### ISSUE THREAD

**Issue by andreineculau** [zkat/pacote-old#104]
https://github.com/zkat/pacote/blame/latest/lib/util/git.js#L138

does the regex match intentionally only on a "X.Y.Z"/"vX.Y.Z" **suffix** ?

As it is now, it means that a git tag "bundle-v1.2.3" would take precedence over "v1.2.3" (because of how `git ls-remote` would sort the refs),

and **I can see benefits for this** (e.g. v1.2.3 would be a tag created via `npm version`, which could get picked up by a CD system, which could end up pushing a bundle-v1.2.3 tag),

but I would like to confirm that it is not just a slip up, thus the behavior is here to stay.

**Comment by zkat** [comment]
I think "doesn't seem like a big deal" and "didn't really cross my mind" are the two answers. I wouldn't mind making this more strict.

**Comment by andreineculau** [comment]
You seem to have twisted my goal 180 around. My goal is to KEEP the current behavior where one can have two same-version tags but one takes precedence, and NOT to have the regex stricter.

--
http://andreineculau.com

**Comment by zkat** [comment]
Ok then. Let's close this then 👍 I have no strong opinion either way.
