### ISSUE TITLE
how to solve it ? when i run npm install

### ISSUE THREAD

**Issue by 17biubiu** [zkat/pacote-old#106]
3067 silly pacote range manifest for convert-source-map@^1.1.0 fetched in 20ms
3068 silly resolveWithNewModule convert-source-map@1.5.0 checking installable status
3069 silly fetchPackageMetaData error for babylon@^6.17.2 Unexpected end of input at 1:14938
3069 silly fetchPackageMetaData dependencies":{"babel-runtime":"^6.0.0"},"devDependencies":{"ava":"^0
3069 silly fetchPackageMetaData                                                                      ^
3070 silly pacote range manifest for source-map@^0.5.0 fetched in 18ms
3071 silly resolveWithNewModule source-map@0.5.6 checking installable status
3072 silly pacote range manifest for private@^0.1.6 fetched in 19ms
3073 silly resolveWithNewModule private@0.1.7 checking installable status
3074 silly pacote range manifest for slash@^1.0.0 fetched in 21ms
3075 silly resolveWithNewModule slash@1.0.0 checking installable status
3076 verbose stack SyntaxError: Unexpected end of input at 1:14938
3076 verbose stack dependencies":{"babel-runtime":"^6.0.0"},"devDependencies":{"ava":"^0
3076 verbose stack                                                                      ^
3076 verbose stack     at SyntaxError (native)
3076 verbose stack     at Object.parseJSON (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/node_modules/jju/lib/parse.js:745:13)
3076 verbose stack     at parse (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/index.js:10:13)
3076 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)

npm: v 5.3.0
node: v8.2.1

**Comment by zkat** [comment]
This means the metadata request succeeded but didn't actually transfer all the data. This is common with broken proxies, or national firewalls like China's. Please consider using https://npm.taobao.org/ instead.
