### ISSUE TITLE
prefetch does not return an integrity for file tarballs

### ISSUE THREAD

**Issue by fahrradflucht** [zkat/pacote-old#120]
**Context:**
While you (@zkat) said that you have it on your todo list I thought I would give https://github.com/npm/npm/issues/16723 a shot. I probably just found out what you already know but I thought you could maybe give me a hint where the root cause of the error is. Feel free to just say it's best for you to fix it yourself.

**Trace:**
`npm publish` calls `cache.add` which calls `prefetch` without an integrity which leds to a `prefetchByManifest` call that calls the `Fetcher` implementation in `file.js`. This Fetcher neither emits an integrity nor a manifest.
Is this the problem? Or should the code consuming the output of `prefetch` handle that the result might have no integrity assigned to it?

**Comment by zkat** [comment]
This has since been fixed. `pacote.prefetch()` has also been deprecated in favor of `pacote.tarball()`, and npm adapted to use that API call instead, so this shouldn't be an issue anymore. Cheers!
