### ISSUE TITLE
Question: Does pacote use `Last-Modified` header when resolving packuments?

### ISSUE THREAD

**Issue by arve0** [zkat/pacote-old#121]
https://registry.npmjs.org/package has the `Last-Modified` header, https://registry.npmjs.org/package/version does not. I've looked a bit in the code, and it [seems like](https://github.com/zkat/pacote/blob/latest/lib/fetchers/registry/fetch.js#L7) it cache fetches with [make-fetch-happen](https://github.com/zkat/make-fetch-happen).

Does this mean that resolving `lodash@4.17.x` and thereafter `lodash@^4.17.1` will make two HTTP GET requests, `/lodash/4.17.x` and `/lodash/^4.17.1`? Assuming empty cache for those urls. (4.17.4 is currently latest).

A possible heuristic would be, 

1. Get packument for `^4.17.x`, resolves to `4.17.4`
2. Get packument for `4.17.x`
    a. HTTP HEAD to `/lodash` -> last-modified has not changed
    b. We have `4.17` in cache -> it must be up to date
    c. Resolve to latest `4.17` in cache

I might be overthinking this, but I'm wondering if it can be some optimizations here. A simple test in 3G mobile connection:
```
time curl -I https://registry.npmjs.com/webpack
```
averages to 400 ms over ten loops and
```
time curl -H "Accept-Encoding: gzip" https://registry.npmjs.com/webpack/* > packument.json.gz
```
averages to 1200 ms.

**Comment by zkat** [comment]
pacote only makes one request per package. It fetches the complete packument and does its own version resolution using [npm-pick-manifest](https://npm.im/npm-pick-manifest). It doesn't hit version-specific endpoints (`.../foo-pkg/1.2.3`), or semver-selection endpoints (`.../foo-pkg/^1.2`), at all.

It also does actually obey cache headers (thanks to m-f-h, which implements a large chunk of [rfc 7234](https://tools.ietf.org/html/rfc7234)), and even memoizes packuments during runs so it won't even do a round-trip to disk if you have multiple versions of the same package being requested in different places in your tree: it'll all be done in-memory, with fairly fast algorithms.

**Comment by arve0** [comment]
Thanks for your swift reply!

> It fetches the complete packument

So the initial cost is quite high? (Still 3G):

```
$ time curl -H "Accept-Encoding: gzip" https://registry.npmjs.com/webpack > complete-packument.json.gz && ls -lh complete-packument.json.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 56689  100 56689    0     0  25582      0  0:00:02  0:00:02 --:--:-- 25593

real	0m2.259s
user	0m0.068s
sys	0m0.027s
-rw-r--r--  1 arve  staff    55K Oct 11 12:51 complete-packument.json.gz
```

And updates to registry will force cache to update whole packument?

**Comment by arve0** [comment]
I'll answer my self 😄 

> So the initial cost is quite high?

Yes. `pacote.manifest` will allways fetch `/package`, when packument is not in memory.

Test:
```js
let p = require('pacote')

async function test () {
  await p.manifest('webpack@latest')
  console.log('got manifest')
  await p.manifest('webpack@latest')
  console.log('got manifest')
}

test()
```

Add logger to node_modules/node-fetch-npm/src/index.js, before `const req = send(options)`:
```js
    console.log(`sending ${options.method} request to ${options.href}`)
```

Will produce:
```
$ node testpacotefetching.js
sending GET request to https://registry.npmjs.org/webpack
got manifest
got manifest
```

Reason I ask, is I'm creating a tool, [download-size](/arve0/download-size), which calculates download size for npm packages upfront before downloading. I'm creating this tool to [raise awareness around bloat](https://news.ycombinator.com/item?id=15445965) in some packages. When resolving dependencies, for example webpack, 344 packuments is downloaded, which is 410 kB (gzipped) over the wire.

For the tool, this doesn't make sense. Say you are on a slow connection, you want to check download size, but to know, you need to download 410 kB of packuments.

**EDIT:** My numbers are wrong, I did not use `Accept: 'application/vnd.npm.install-v1+json'` header.
**EDIT2:** I've corrected bytes over the wire from 1,6 MB to 410 kB.

**Comment by arve0** [comment]
If whole packuments are stored to cache(?), this might be an easy fix. Something like

```js
let headers = await fetchHead(`https://registry.npmjs.org/${packageName}`).headers
let storedManifest = await getManifestFromCache(packageName)
if (headers['last-modified'] === storedManifest['_last-modified']) {
  return npmPickManifest(storedManifest, wanted)
} else {
  let manifest = await fetchManifest(`https://registry.npmjs.org/${packageName}`)
  return npmPickManifest(manifest, wanted)
}
```

This will
1. reduce initial download size on slow connections
2. reduce load on registry, assuming HEAD requests are cheeper than GET requests.

**Comment by zkat** [comment]
Like I said: We already use HTTP headers related to caching, not just `last-modified`, to reduce transfer: if the local version is stale, we make a request with the appropriate headers, which, most of the time, will result in a 304 (meaning: it just confirms that our local cache is up to date). So you only ever download a particular packument once, ever. You'll only download new packuments if there's been new versions published, or when other such modifications happen (like a deprecation).

The cache pacote uses is pretty damn aggressive about this, but makes sure to be spec-compliant.

**Comment by arve0** [comment]
> So you only ever download a particular packument once, ever.

Are you sure about that? My example above seems to refute that. Does not node-fetch-npm [do a http request at line 54](https://github.com/npm/node-fetch-npm/blob/latest/src/index.js#L54)?

To reproduce:
```
$ mkdir temp
$ cd temp
$ npm i pacote
$ sed -iE '52i\
$ console.log(`${options.method} to ${options.href}`)' node_modules/node-fetch-npm/src/index.js
$ echo "let p = require('pacote'); p.manifest('webpack@latest')" > index.js
$ node index.js
GET to https://registry.npmjs.org/webpack
$ node index.js
GET to https://registry.npmjs.org/webpack
```
https://asciinema.org/a/cM2uxT3eNyK45gBf9VLqTaih5

**Comment by zkat** [comment]
@arve0 You're not passing in an `opts.cache` value. You need to give it a cache for it to write/read its local disk cache.

You also need to look at the http code for these requests. You'll need to wait 300s+ or something like that before we start making external requests again, and then you should see `304` as the response code.

**Comment by arve0** [comment]
Aha! Thanks 😹 

Want this in the README?

##### `opts.cache`
Path to cache. NPM default location is `path.join(process.env.APPDATA || process.env.HOME, '.npm', '_cacache')`.

**Comment by zkat** [comment]
there'll be a pass through the docs at some point to get them all up to date and add missing details.
