### ISSUE TITLE
jsonFromStream doesn't handle symlinks

### ISSUE THREAD

**Issue by iby** [zkat/pacote-old#135]
When `package.json` is a symlink `jsonFromStream` [will fail](https://github.com/zkat/pacote/blob/ad069258a14b77a4445ba38531329394aa9417fd/lib/finalize-manifest.js#L198-L222) to load data, because that entry won't return any. It could in theory check `entry.header.linkpath` and use that value over `filename` argument for all following entries, but the needed entry might be already processed, in which case it will end up not finding it.

**Comment by zkat** [comment]
For security reasons, symlinks in npm packages are not supported -- npm itself should not pack them (and indeed, [`npm-packlist` explicitly ignores them all](https://github.com/npm/npm-packlist/blob/master/index.js#L146)), and [pacote itself filters them out on extraction](https://github.com/zkat/pacote/blob/ad069258a14b77a4445ba38531329394aa9417fd/lib/extract-stream.js#L18) on the off chance that the package was made with something other than npm.

But maybe I misunderstand: what's causing you to run into this as an error?

**Comment by iby** [comment]
I knew npm was hard on that convention, but didn't know the specifics. Makes perfect sense now, thanks!
