### ISSUE TITLE
git: Does pacote respect per-project .npmrc file "git" parameter?

### ISSUE THREAD

**Issue by TASlavens** [zkat/pacote-old#155]
Hello,

It appears to me that in file ./lib/util/git.js lines 65-68, the "git" config parameter is never retrieved - that code only checks the path environment variable.  Later in the same file on line 245 the empty GIT_PATH causes an ENOGIT error because git was not found in the path environment variable.  However, I believe pacote should respect the "git" parameter in the per-project .npmrc file (well, all of the npm config files, of course).  The behavior I'm seeing is exactly what I would expect from that code:  on a system without git.exe found in any path in the path environment variable, pacote (actually, "npm install" with a package.json containing dependencies on github.com) returns ENOGIT.

My (admittedly shallow) look at the ./lib/util/git.js code tells me this is not a platform-specific problem.  FWIW, I'm seeing this under npm 5.7.1 and I also checked that ./lib/util/git.js on github still has the same relevant code (line numbers referenced in prior paragraph) as of commit 788fd13 (17th Apr 2018).  The relevant line numbers in the file as provided with npm 5.7.1 (looks like commit 83be46b on 06th Feb 2018) are 47-50 and 203.

Other info:  This is happening on a Win2012R2 build server VM as part of a TFS build (agents for two TFS servers, versions 2017u3.1 and 2018u2; TFS agents on same server VM).  For reasons too long to go into here, we cannot have the path to git.exe in the machine or user path environment variable, and due to the way TFS build agents work, adding it to the process environment variables is infeasible.  Regardless of my difficulties, I think pacote should respect .npmrc file parameters.

Thanks in advance for looking into it.

**Comment by zkat** [comment]
pacote does not read or respect `.npmrc`. You have to manage that manually and parse your own configs. We have a pending project to extract the config reading and parsing into a standalone package, but until then, you're on your own.
