### ISSUE TITLE
Transitive dependency (genfun@4.0.1) license prevents use of pacote

### ISSUE THREAD

**Issue by clydin** [zkat/pacote-old#163]
The dependency `protoduck@5.0.0->genfun@4.0.1` is licensed with the CC0-1.0 license which the Angular CLI team cannot use.  The latest version (`genfun@5.0.0`) has been relicensed under MIT which would allow use of `pacote`.   Unfortunately, `protoduck@5.0.0` has a semver range of `^4.0.1` which prevents the latest version from being used with the new license.
A [PR](https://github.com/zkat/protoduck/pull/5) against `protoduck` has been created to update `genfun` to the latest version.

The Angular CLI team would very much like to use the comprehensive set of features provided by `pacote`.  Any help in this regard would be greatly appreciated.

**Comment by zkat** [comment]
I've released `pacote@9.1.1`, which bumps a lot of its deps, including protoduck and genfun, so you should be good now! lmk if you have anything else you need.

**Comment by clydin** [comment]
Awesome. Thank you.
