### ISSUE TITLE
Convert project to strict mode

### ISSUE THREAD

**Issue by zkat** [zkat/pacote-old#19]
All source files should have `'use strict'` added to the first line of each file. Ditto for test code.

**Comment by varjmes** [comment]
Going to do this tonight, I think.

**Comment by varjmes** [comment]
You say 'all source files', does this basically mean every `.js` file? Or not the module.exports files like `tarball.js`? Working on the assumption you mean all. Can revert if not the case.

**Comment by varjmes** [comment]
#26

**Comment by zkat** [comment]
Fixed by #26 and #27. Thanks! :D
