### ISSUE TITLE
Implement git handlers

### ISSUE THREAD

**Issue by zkat** [zkat/pacote-old#4]
This one's a tricky one. There are many ways to get the contents of a git repo. The best way for pacote to handle git is by judiciously picking which of these to use depending on what's being requested, and trying to avoid a full git clone at all costs.

Semver range dependencies should be resolved according to https://github.com/npm/npm/pull/15308. These can be resolved with a `git ls-remote`.

These are the possible ways I've found so far to get either full package data, or subsets, and associated caveats:

### fullfat clone

`$ git clone https://github.com/npm/npm`

  * will work pretty much universally
  * may need to try fallback protocols for hosted git
  * is bloody slow (`npm/npm`: 13s, `zkat/cacache`: 1.7s (so it won't be so bad on small repos))
  * needs its own entire caching scheme to retain repos, if desired (can be postponed?)

### shallow clone

`$ git clone https://github.com/npm/npm --depth=1 -b <named-ref>`

  * Only works for `HEAD` or named refs. Any commit hash that has an existing remote ref will work, too.
  * Will **always** work for semver-range git, because all tags are named refs. 🎉 
  * much much faster than `git clone` for larger repos but still fairly heavy. (`npm/npm`: 4.35s, `zkat/cacache`: 1.52s)
  * github folks might not like us very much if we do this a lot?
  * can tar + cache directly and remove cloned dir from tmp
  * I thought I could fall back to a HEAD clone + git fetch but alas that is also not possible without a named ref.

### [`git archive`](https://git-scm.com/docs/git-archive)

`$ git archive --format=tar.gz --prefix=package/ --remote=https://github.com/npm/npm <committish>`

  * direct tarball download
  * **BIG CAVEAT**: must be *manually* enabled *server-side*. github does not enable it. Seems to fail very quickly when not enabled, though.
  * works on non-hosted git when enabled
  * uses regular git authentication mechanism
  * Probably a really fantastic idea for private corporate git servers
  * `package/` prefix can be added with `--prefix=` option.
  * There is also a [terrifying monstrosity](http://stackoverflow.com/questions/14405782/git-fetch-single-file-from-remote-repository-programatically) that lets you fetch individual files, but I document this here purely for the horror value. It's not worth it.

### hosted git tarballs

`$ curl -LO https://github.com/npm/npm/archive/<committish>.tgz`

  * github caches these! they can be pretty fast! (`npm/npm`: 0.6s, `zkat/cacache`: 0.39s)
  * I have no idea right now how to authenticate these for private repos
  * can target any committish (not just named refs)
  * only available on hosted git types supported by [`hosted-git-info`](https://npm.im/hosted-git-info)
  * can lean on pacote's existing http caching mechanisms, transparently
  * contents will not be inside `package/` by default, so we need to manually add a level

### individual direct file download

`$ curl -LO https://raw.githubusercontent.com/npm/npm/<committish>/package.json`

  * only for fetching `package.json` and `npm-shrinkwrap.json`
  * can't even fill out `bin` when `directories.bin` is there.
  * only works on hosted gits that support it.
  * allows fast filling out of some manifests without having to fetch a full tarball.

### remote ref lookup

` $ git ls-remote https://github.com/npm/npm -t -h '*'`

* Fetches a full ref list from a remote
* Not as fast as you'd think (`npm/npm`: 0.83s, `zkat/cacache`: 0.37s)
* Useful for finding named refs (for semver support or to possibly avoid a [full clone](#fullfat-clone))
* No speed difference between `-t -h` and `-t`. The former will use more RAM but increase chances of a non-semver committish matching. The latter will be smaller and be all that's needed for a semver ref.

### When I think about implementing this
[![everybody panic](https://dutchreview.com/wp-content/uploads/Panic.gif)]()

**Comment by anaisbetts** [comment]
> I have no idea right now how to authenticate these for private repos

I'm like...62% sure you can do `&token=GITHUB-TOKEN` or `&access-token=GITHUB-TOKEN`. You can also see a similar syntax when you get a raw file link from a private repo

**Comment by zkat** [comment]
@paulcbetts Thanks! I'll do some research on this to see what the possibilities are. From a usability PoV, it feels like a big ask to tell someone to set up a `GITHUB_TOKEN` env var or option or something like that, but it probably makes sense if your use case is really heavy private git repo use. But it's worth keeping the option open. Maybe there's a way to piggyback on [the way github does https git clones](https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-urls-recommended) simply 'cause folks will likely have that configured if they're working on the source repo as well.
