### ISSUE TITLE
cache fallback for offline modes

### ISSUE THREAD

**Issue by zkat** [zkat/pacote-old#47]
`preferOffline` and `offline` both change the fetch mechanism to in one way or another, lean towards maximizing use of the local caches.

There is an issue, though, where package metadata may have been fetched into the cache, but a corresponding matching latest package may not have been downloaded. In these cases, it turns out, we may in fact have a semver-compatible tarball available in the cache that _at least_ `offline` could fall back to in this particular corner case.

This case, though, is probably pretty rare. I think. Just an idea out there that's pretty low-priority. And I might be wrong about how rare that situation really is.

**Comment by yindia** [comment]
you are not wrong. it can be consider as worst a case. but probability is very low. so we can skip it until someone rise any issue.

**Comment by zkat** [comment]
I agree
