### ISSUE TITLE
Write tests for prefetch()

### ISSUE THREAD

**Issue by zkat** [zkat/pacote-old#52]
It's just kinda hanging out there on `latest` right now, and it needs some test coverage :<

**Comment by nlkluth** [comment]
Gonna look into this one and see if I can help :)

**Comment by zkat** [comment]
@nlkluth thanks! This is super helpful! Let me know if you have questions. :)

**Comment by nlkluth** [comment]
I have made some progress but am looking for a bit of feedback if you don't mind 😃 

https://github.com/nlkluth/pacote/blob/latest/test/prefetch.js#L92

I am not sure I am taking the right approach or if there is a better way to handle mocking the cache and validating prefetch's results. Also the line linked is to a commented out test; I can't wrap my head around what digest to update and crypto is a bit above my level :) Same issue here too, is there a better way to check that it's hitting the right path in prefetch while not caring about the cache itself?

Let me know if there are other test scenarios you'd like me to cover too, I'm just going off of coverage as  I continue to try and understand things.

Thanks!

**Comment by zkat** [comment]
Hey @nlkluth! These look great! Thanks for taking the time to do this.

Your test looks fine, and it actually exposed a bug-slash-thinko in the way prefetch works: it's using `OPTS.digest` not just against the _tarball_ (which it never fetches), but _against the manifest request_. Which is an error because the tarball shasum and the sha of the content of the _manifest_ request are obvs going to be completely different things. I think you literally just made me realize what was going on with a bug that I'd run into during integration. Basically, `opts.digest` should only ever be applied against the _tarball_ itself.

The system works!

I'd suggest you try to fix it, but the reality is that this + a couple of other awful things about that request client have made me want to just rewrite the whole thing over again to make it more predictable, better about errors, etc. I think you should leave this test around (or better yet: use the test-skip syntax to give a reason why it was skipped, because it'll fail until the bug is fixed. In tap, this looks like `test('this is the test', { skip: 'prefetch with digests is broken right now' }, t => {...})`)

### Yay tests!

These are good tests. You're covering the important bits of prefetch, and you did that well enough to uncover a bug. :)

I really like that you hosted the tarballs under a separate domain than the manifests. I think that's a really good thing to test for. 🎉 

So far so good!

### Optional nits

So I'm gonna have to rewrite that client before these all pass. In the meantime, if you want more ideas on how to tweak the tests further, here's some ideas. All of these are *entirely optional* and more about doing things more like the rest of the test suite. Whether you do them or not doesn't really detract from the quality of the tests:

There's a nice `mockTar()` utility in the test/util directory that might make it easier to generate those tarballs (and get rid of the need for that initial tarball-generator test. It's probably nicer to just mock them for every individual test.). See https://github.com/nlkluth/pacote/blob/latest/test/registry.tarball.js#L53

https://github.com/nlkluth/pacote/blob/latest/test/registry.tarball.js#L33 This little incantation is also useful and used throughout the tests so that you can do `LOGLEVEL=silly node test/prefetch.js` to get really verbose logging when trying to debug these. It also muffles the http log statements with the default npmlog loglevel.

Finally, `t.plan()` is pretty harmless here, and probably nice as an extra check, but I tend to omit it when using `return <promise>` because the promises already take care to make sure there's either a failure OR all your assertions pass. t.plan() tends to be more useful when you're doing a bunch of concurrent errback-based things (as in, node-style `(err, cb) => {}` callbacks), since those are... hard to compose well. Up to you whether you like the extra layer of verification for your tests :)

**Comment by zkat** [comment]
@nlkluth Update: I've pushed a fix to `latest` on the main branch. You should be able to rebase and get that test passing. lmk if it still doesn't work -- it seemed to be ok locally. Thanks again ^_^;;;

**Comment by nlkluth** [comment]
Awesome, thanks for the feedback! I'll get this cleaned up soon 😄
