### ISSUE TITLE
Bulk request fetching

### ISSUE THREAD

**Issue by zkat** [zkat/pacote-old#56]
bulk stuff is way faster than stream-based stuff. Should do #25 before doing this just so we have solid numbers on the difference, and stream stuff needs to still exist because we want to be able to handle multi-gig files.

Ideally, `pacote.extract` and `pacote.prefetch` would only use streams for particularly big packages. `pacote.manifest` should always use bulk requests.

**Comment by boutell** [comment]
Bulk stuff as in... big buffer sizes passed to .read()? Just curious what this is about.

(Is it possible to tell a stream to use a bigger buffer size to reduce redundant code?)

**Comment by zkat** [comment]
@boutell it depends! `fs.{read,write}File()` are significantly faster than `fs.create{Read,Write}Stream()`. On the order of ~3x speedup for the former. And that's the case even when you bump things up such that it's a single `_write`. There's benchmarks over at [cacache](https://github.com/zkat/cacache) that test reads and writes both in streaming and bulk mode, too, and cacache itself is already 3-4x faster when doing bulk operations on both read and write. (just clone the repo, do `npm i && npm run benchmarks`)

The story with network requests is a little different. Probably because of all the stuff `npm-registry-client` is doing for restarting and parsing bulk requests, `streaming: true` is ~2x+ faster (more? I had a benchmark somewhere).

So pacote would need to make judicious use of _both_ streams and bulk writes, depending on the data size (which fortunately we usually have, because of `Content-Length`).

I already have a benchmark suite branch that I need to nudge a little more before it's ready to merge, but that's gonna be super important in finding the right combination for all this :)

**Comment by zkat** [comment]
Maybe I'll just push it up cause it might start being useful to folks who are interested in doing this sort of optimization golf 😁

**Comment by zkat** [comment]
https://github.com/zkat/pacote/pull/61 There we go. This should help.
