### ISSUE TITLE
feature: switch to node-tar@2

### ISSUE THREAD

**Issue by zkat** [zkat/pacote-old#74]
There's cool stuff happening over in node-tar land. Once it's solid and released, let's shove it in pacote and bask in its absurdly performant glory.

**Comment by SimenB** [comment]
Done in 28c80a9dfb8d687b0ba2ee50fb1e65b55b5bd9ff & 53899c75a2ac9ca2121281d559d30486a97b7c45?

**Comment by zkat** [comment]
Oh yes! Thank you for pointing that out. 🎉
