### ISSUE TITLE
registryKey is dropping path from URL

### ISSUE THREAD

**Issue by zarenner** [zkat/pacote-old#84]
In registry-key.js, there's currently the following call to url.format, which currently is dropping the path:
``` 
const formatted = url.format({
    host: parsed.host,
    path: parsed.path,
    slashes: parsed.slashes
  })`
```
It looks like (presumably after https://github.com/nodejs/node/pull/303) 'path' is no longer supported, and we need to use 'pathname' instead.
https://nodejs.org/api/url.html#url_url_format_urlobject

**Comment by zkat** [comment]
Thanks for the report! I would *love* to get a patch for this. I'd rather get community participation than fix it myself, and you did a great job of outlining the fix for it.

**Comment by zkat** [comment]
For the sake of cross-linking: fixing this bug will fix https://github.com/npm/npm/issues/16528
