### ISSUE TITLE
Significant slowdown from compressed tarballs

### ISSUE THREAD

**Issue by zkat** [zkat/pacote-old#86]
The benchmark results in this tweet: https://twitter.com/fold_left/status/860239327229607937

```
npm5: 15.561s
npm5-cached: 16.351s
npm5-shrinkpack: 1.216s
npm5-shrinkpack-compressed: 8.817s
```

Seem to hint that there's a significant slowdown when tarballs are already gzipped.

I'm not terribly surprised by a slowdown, but the specific slowdown seems pretty big. I wonder if there's something along the way slowing things down more than expected.

**Comment by zkat** [comment]
cc @JamieMason

**Comment by JamieMason** [comment]
You can probably close this @zkat(?)

**Comment by zkat** [comment]
oh yeah. I guess that's the case!
