### ISSUE TITLE
Authorization header is forwarded on redirect to different host

### ISSUE THREAD

**Issue by zarenner** [zkat/pacote-old#87]
@simonua @zkat 
Some npm registries redirect to another host for package tarball downloads. For example, Microsoft VSTS redirects to Azure Blob.

pacote (or possibly make-fetch-happen/node-fetch) appears to forward authorization headers on a redirect to another host, unlike previous versions of npm. In the specific case of Azure Blob, these credentials are invalid (the correct token is provided in the URI querystring), and an Authorization header must not be present.
This results in an error like:
> npm ERR! 400 Authentication information is not given in the correct format. Check the value of Authorization header.

More generally, from a security perspective forwarding credentials (by default, at least) to another host isn't great.

**Comment by zarenner** [comment]
@zkat @simonua I don't think I'll likely have time today to take a deeper look at this, but I'll try to tomorrow or Monday.

**Comment by zkat** [comment]
pacote should be emulating the behavior in npm itself for this. This was intended to be handled in https://github.com/zkat/pacote/blob/latest/lib/fetchers/registry/fetch.js#L74-L78

I'm not sure why it's not working right now. I'll look into it. :)

**Comment by zkat** [comment]
It would be useful to see a pair of URLs here

**Comment by zarenner** [comment]
Thanks! FYI I don't see getHeaders getting called on the redirect.

An example:
https://zlrenner.pkgs.visualstudio.com/_packaging/aaa/npm/registry/npmtest/-/npmtest-1.0.0.tgz responds with a 302 to Location https://vsblobprodscussu0shard19.blob.core.windows.net/b-ce7824a198f144319abb2dd6dbc33de7/9D4EBD0553ED8F94889EC70CDA985199EF1284A516751904BDBB4F28192BC4B000.blob?sv=2015-12-11&sr=b&si=1&sig=redacted&spr=https&se=2017-05-05T03%3A10%3A10Z

**Comment by zkat** [comment]
ohhhhh. It's in the _redirect_.

It makes more sense that this would be forwarding headers like that. I wonder why `request` doesn't send them (we use `node-fetch` under the hood now, instead). I'll look into it more.

I'm assuming `zlrenner.pkgs.visualstudio.com` is the same host as the manifest, and that blob.core is where we _shouldn't_ pass the creds to?

**Comment by zkat** [comment]
Aha, here's where `request` does it:

https://github.com/request/request/blob/b12a6245d9acdb1e13c6486d427801e123fdafae/lib/redirect.js#L134-L138

**Comment by zkat** [comment]
https://github.com/npm/node-fetch-npm/issues/1 I've traced the source to node-fetch-npm itself, and pointed out where in the code it probably needs to be patched.

**Comment by zkat** [comment]
It landed. The redirect auth issue should be fixed now. Cheers to @ivanph for the patch :)

**Comment by simonua** [comment]
Awesome! Thank you, everybody! I'll look for a new beta on Monday and give it a try, then report back. Have a great weekend, everyone! 

Cheers, 

Simon

**Comment by simonua** [comment]
@zkat @zarenner @ivanph, I verified I can now install private packages from VSTS Package Management with 5.0.0-beta.44 (presumably works with 43 as well, but 44 was latest available). Way to go! And, thank you!
