### ISSUE TITLE
Cannot install git dependency from Bitbucket Server

### ISSUE THREAD

**Issue by apaleslimghost** [zkat/pacote-old#90]
Steps to reproduce: `npm install` with the following line in `package.json` (`[REDACTED]` is a Bitbucket Server host; this dependency works in npm 4)

```json
"circular-list": "git+ssh://git@[REDACTED]/circular-list.git#v1.0.2",
```

output:

npm ERR! code 128
npm ERR! Command failed: /usr/local/bin/git clone --depth=1 -q -b v1.0.2^{} ssh://git@[REDACTED]/circular-list.git /Users/matthew.brennan/.npm/_cacache/tmp/git-clone-d9115048
npm ERR! warning: templates not found /var/folders/0m/smmrszcj367g1ds3nkjrv2y42l6kl3/T/pacote-git-template-tmp/git-clone-410ac485
npm ERR! fatal: Remote branch v1.0.2^{} not found in upstream origin
npm ERR!
```

`npm version`:

```json
{ npm: '5.0.0',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.9.2',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.1.281.88',
  zlib: '1.2.8' }
```

cloned from npm/npm#16789

**Comment by zkat** [comment]
This'll be fixed in `5.0.1`, once it gets a pacote update 👍  (it's fixed there!)
